
services:
  db:
    image: postgres:15
    container_name: postgres_db
    ports:
      - "9898:5432"
    environment:
      POSTGRES_DB: products
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - db_data:/var/lib/postgresql/data

  app:
    build: .
    container_name: product_service
    ports:
      - "8080:8080"
    depends_on:
      - db

volumes:
  db_data:
